# Generated by Django 3.1.7 on 2021-05-12 17:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('bel', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Белки')),
                ('jir', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Жиры')),
                ('ugl', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Углеводы')),
                ('cal', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Калории')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='Название приема пищи')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время приема')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Приемы пищи',
            },
        ),
        migrations.CreateModel(
            name='Racion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramm', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Грамм')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjuk.food', verbose_name='Блюдо')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjuk.meal', verbose_name='Прием пищи')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(through='bjuk.Racion', to='bjuk.Food', verbose_name='Блюда'),
        ),
    ]
