# Generated by Django 3.1.7 on 2021-03-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjuk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время приема'),
        ),
    ]
